In [3]:
n=int(input("enter the number of elements in a ,ist"))
h=[]
for i in range(n):
    a=int(input())   
    h.append(a)
max=0 
ll=len(h)   
for i in range(ll):
    if h[i] > max:
        max=h[i]
        for i in range(ll):
            min=0
            if h[i] > max:
                min=h[i]
        
print(max)
print(min)

6
0


In [6]:
import numpy as np
a= np.array([[1,2,3,4],[1,2,3,4]])
b=np.array([1,2,3,4])
a+b

array([[2, 4, 6, 8],
       [2, 4, 6, 8]])

In [20]:
a=np.tile(np.arange(0,30,10),(2,2))
b=np.tile(np.arange(1,34,6),(2,1))

print(a+b)

[[ 1 17 33 19 35 51]
 [ 1 17 33 19 35 51]]


In [21]:
a=np.arange(0,40,10)
print(a.shape)

(4,)


In [ ]:
a=a[:,np.newaxis]

In [23]:
print(a.shape)

(4, 1)


In [24]:
a=a[:,:,np.newaxis]

In [25]:
a.shape

(4, 1, 1)

ravel

In [26]:
a=np.array([[1,2,3,4],[1,2,3,4]])
a.ravel()

array([1, 2, 3, 4, 1, 2, 3, 4])

In [27]:
a=np.arange(0,4)
a.resize(8,)
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [28]:
a.resize(4,)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [30]:
a=np.array([[2,3,4,1],[1,4,2,6]])
b=np.sort(a,axis=1)
b

array([[1, 2, 3, 4],
       [1, 2, 4, 6]])

In [31]:
a=np.array([[2,3,4,1],[1,4,2,6]])
b=np.sort(a,axis=0)
b

array([[1, 3, 2, 1],
       [2, 4, 4, 6]])

In [ ]:
a=np.array([2,4,6,3])
b=np.argsort(a)    # returns the indices of sorted array
b

array([0, 3, 1, 2])

In [33]:
a[b]

array([2, 3, 4, 6])