create a 1 d array containing all even numbers between 10 to 100

In [ ]:
import numpy as np
a=np.arange(10,101,2)
a.3

array([ 10,  12,  14,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98, 100])

create a 5*5 array filled with multiples of 3

In [53]:
x=np.arange(3,3*25+1,3).reshape(5,5)
x


array([[ 3,  6,  9, 12, 15],
       [18, 21, 24, 27, 30],
       [33, 36, 39, 42, 45],
       [48, 51, 54, 57, 60],
       [63, 66, 69, 72, 75]])

generate 4*4 matrix where the diagonal values are 1 and rest are zero

In [56]:
v=np.eye(4)
v

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

create a 3d array of shape(2,3,4) filled with random integers from zero to 20

In [69]:
s=np.random.randint(0,30,size=(2,3,4))
#s.reshape(2,3,4)
s

array([[[20,  8,  4, 13],
        [16, 29, 27,  6],
        [11,  4, 17, 15]],

       [[15,  7, 20, 20],
        [17, 14,  0, 18],
        [15, 17,  2, 14]]], dtype=int32)

reshape 1 d array of 30 elements into shape (5,2,3)and print its shape

In [72]:
s=np.arange(0,30).reshape(5,2,3)
s

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29]]])

create an array of 10 evenly spaced between 5 and 15

In [75]:
x=np.linspace(5,15,10)
x

array([ 5.        ,  6.11111111,  7.22222222,  8.33333333,  9.44444444,
       10.55555556, 11.66666667, 12.77777778, 13.88888889, 15.        ])

input a list of number find the second most highet number in a list

In [ ]:
n=int(input("enter the number of elements in a ,ist"))
h=[]
for i in range(n):
    a=(input())   
    h.append(a)
print(h)
h.sort()
print(h[-1])

['1', '8', '2']
2


In [ ]:
h1=list(input())
h1.sort()
print(h1)
print(h1[-2])

['2', '2']


NameError: name 'n' is not defined

In [15]:
n=int(input("enter the number of elements in a ,ist"))
h=[]
for i in range(n):
    a=int(input())   
    h.append(a)
max=0 
ll=len(h)   
for i in range(ll):
    if h[i] > max:
        max=h[i]
print(max)




8
