In [3]:
!pip install numpy


   ---------------------------------------- 0.0/12.8 MB ? eta -:--:--
   ----------- ---------------------------- 3.7/12.8 MB 20.7 MB/s eta 0:00:01
   ---------------------- ----------------- 7.3/12.8 MB 18.7 MB/s eta 0:00:01
   ------------------------------------ --- 11.5/12.8 MB 19.4 MB/s eta 0:00:01
   ---------------------------------------- 12.8/12.8 MB 19.2 MB/s  0:00:00


## arange= array of range

In [ ]:
import numpy as np
a=np.array([1,2,3,4]) # creates an array
print(a)

print(np.arange(10)) # range function in arrray 


[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [12]:
L=range(1000)
square=[]

for i in range(1000):
    square.append(i**2)

print(square)



[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 2656

list comperhension

we can also write this code as

In [ ]:
L=range(1000)
square=[i**2 for i in L] # list comperhension
print(square)


[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 23716, 24025, 24336, 24649, 24964, 25281, 25600, 25921, 26244, 2656

only even numbers

In [20]:
L=range(1000)
square=[i**2 for i in L if i % 2==0] # list comperhension
print(square)


[0, 4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500, 2704, 2916, 3136, 3364, 3600, 3844, 4096, 4356, 4624, 4900, 5184, 5476, 5776, 6084, 6400, 6724, 7056, 7396, 7744, 8100, 8464, 8836, 9216, 9604, 10000, 10404, 10816, 11236, 11664, 12100, 12544, 12996, 13456, 13924, 14400, 14884, 15376, 15876, 16384, 16900, 17424, 17956, 18496, 19044, 19600, 20164, 20736, 21316, 21904, 22500, 23104, 23716, 24336, 24964, 25600, 26244, 26896, 27556, 28224, 28900, 29584, 30276, 30976, 31684, 32400, 33124, 33856, 34596, 35344, 36100, 36864, 37636, 38416, 39204, 40000, 40804, 41616, 42436, 43264, 44100, 44944, 45796, 46656, 47524, 48400, 49284, 50176, 51076, 51984, 52900, 53824, 54756, 55696, 56644, 57600, 58564, 59536, 60516, 61504, 62500, 63504, 64516, 65536, 66564, 67600, 68644, 69696, 70756, 71824, 72900, 73984, 75076, 76176, 77284, 78400, 79524, 80656, 81796, 82944, 84100, 85264, 86436, 87616, 88804, 90000, 91204, 92416, 9

 # creating arrays


In [26]:
a=np.array([0,1,2,3])
print("array",a)
print("dimension",a.ndim)
print("shape",a.shape)

array [0 1 2 3]
dimension 1
shape (4,)


## 2d

In [28]:
a=np.array([[0,2,3,4],[1,2,3,4]])
print("array",a)
print("dimension",a.ndim)
print("shape",a.shape)

array [[0 2 3 4]
 [1 2 3 4]]
dimension 2
shape (2, 4)


## 3d

In [ ]:
a=np.array([[[0,2,3,4],[1,2,3,4]],[[0,1,2,3],[3,12,3,3]]])
print("array",a)
print("dimension",a.ndim)
print("shape",a.shape)

array [[[ 0  2  3  4]
  [ 1  2  3  4]]

 [[ 0  1  2  3]
  [ 3 12  3  3]]]
dimension 3
shape (2, 2, 4)


In [33]:
a=np.arange(10)
print(10)

10


In [35]:
a=np.arange(1,10,2)
print(a)

[1 3 5 7 9]


C:\Users\91859\vscode\numpy.ipynb