In [2]:
import numpy as np
a=np.array([1,2,3,4])
print(a)
print(np.arange(10))

[1 2 3 4]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
L=range(10)
[i**2 for i in L if i%2==0]

[0, 4, 16, 36, 64]

In [5]:
L=range(10)
[i**2 for i in L if i%2==1]

[1, 9, 25, 49, 81]

In [7]:
a=np.array([1,2,3,4])
%timeit [i**2 for i in L]


296 ns ± 10.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [13]:
a=np.array([[[1,2,3],[3,4,5]],[[2,3,4],[2.,3,4]]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(len(a))


(2, 2, 3)
3
float64
2


In [15]:
l=np.arange(100)
print(l)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [16]:
a=np.arange(0,10,2)
a

array([0, 2, 4, 6, 8])

In [22]:
import numpy as np
a=np.linspace(0,10,4)
a

array([ 0.        ,  3.33333333,  6.66666667, 10.        ])

In [24]:
a=np.ones((3,4))
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
a=np.eye(3,3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
a=np.diag([1,2,3])
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [33]:
a=np.random.random((3,4))
a

array([[0.70906181, 0.10513588, 0.85444586, 0.25247411],
       [0.00179311, 0.6324872 , 0.60667904, 0.10617043],
       [0.15011794, 0.92928873, 0.94247724, 0.31810285]])

In [38]:
a=np.arange(10,dtype=int)
a.dtype

dtype('int64')

In [34]:
a=np.arange(10)
a.dtype

dtype('int64')

In [45]:
a=np.array([1,2,3])
print(a[2:])

[3]


In [46]:
print(a[::2])

[1 3]


In [47]:
print(a[2])

3


In [54]:
a=np.arange(10)
b=np.arange(5)
a[5:]=b[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])