In [2]:
import numpy as np
a=np.arange(10)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
b=a[::3]
b

array([0, 3, 6, 9])

In [6]:
np.shares_memory(a,b)

True

In [14]:
b[2]=10
b

array([ 0,  3, 10, 10])

In [15]:
a


array([ 0,  1,  2,  3,  4,  5, 10,  7,  8, 10])

In [16]:
c=a[::2].copy()
c

array([ 0,  2,  4, 10,  8])

In [18]:
np.shares_memory(a,c)

False

In [19]:
c[2]=10
c


array([ 0,  2, 10, 10,  8])

In [20]:
a


array([ 0,  1,  2,  3,  4,  5, 10,  7,  8, 10])

In [22]:
a=np.random.randint(1,19,4)
a

array([ 6, 18,  2,  3], dtype=int32)

In [23]:
a=np.random.randint(1,20,15)

In [30]:
m=(a%2==0)
print(a[m])

[14  6 16 10 16 18  2  6]


In [35]:
a[m]=-1
a

array([-1, -1, 15, -1,  5, -1, 11, -1, -1, 17, -1, 13, -1, 15, 19],
      dtype=int32)

In [36]:
a=np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [37]:
a[[2,3,4,5,6,7]]

array([20, 30, 40, 50, 60, 70])

In [39]:
a[[2,3]]=200,21
a

array([  0,  10, 200,  21,  40,  50,  60,  70,  80,  90])

In [40]:
a=np.arange(10)
b=np.arange(10)
print(a+b)

[ 0  2  4  6  8 10 12 14 16 18]


In [41]:
a*10

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [43]:
b=np.ones(4)+1
print(b)

[2. 2. 2. 2.]


In [52]:
c=np.diag([1,2,3,4])
print(c*c)
print("**************")
print(c.dot(c))

[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]
**************
[[ 1  0  0  0]
 [ 0  4  0  0]
 [ 0  0  9  0]
 [ 0  0  0 16]]


In [53]:
a=np.array([1,2,3,4])
b=np.array([5,3,5,4])
a==b

array([False, False, False,  True])

In [54]:
a>b

array([False, False, False, False])

In [57]:
a=np.array([1,2,3,4])
b=np.array([5,2,2,4])
c=np.array([1,2,3,4])
np.array_equal(b,c)

False

In [58]:
a=np.array([1,1,0,0])
b=np.array([1,0,0,1])
np.logical_or(a,b)

array([ True,  True, False,  True])

In [60]:
np.logical_and(a,b)

array([ True, False, False, False])

In [61]:
np.logical_xor(a,b)

array([False,  True, False,  True])

In [62]:
a=np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [63]:
np.log(a)

C:\Users\91859\AppData\Local\Temp\ipykernel_25352\176755284.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [64]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [65]:
x=np.array([1,2,3,4])
print(np.sum(x))

10


In [80]:
x=np.array([[4,5],[2,3]])
x

array([[4, 5],
       [2, 3]])

In [81]:
x.sum(axis=0)

array([6, 8])

In [84]:
x.sum(axis=0)

array([6, 8])

In [86]:
a=np.array([2,3,4,5,6])
x.min()


np.int64(2)

In [88]:
x.max()

np.int64(5)

In [91]:
x.argmin()

np.int64(2)

In [92]:
x.argmax()

np.int64(1)

In [ ]:
np.all()
